server:
  port: 4000

spring:
  application:
    name: sct-auth
  main:
    allow-bean-definition-overriding: true

  profiles:
    active: dev
  cloud:
    config:
      name: ${spring.application.name}
      profile: ${spring.profiles.active}

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://sct-eureka:8761/eureka/
